server:
  port: 8062
  
# Spring properties
spring:
  application:
     name: contact-service

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1009/eureka/  
  instance:    hostname: localhost    
  