server:
  port: 8061
  
# Spring properties
spring:
  application:
     name: user-service  mail:    host: smtp.gmail.com
    port: 587
    username: test.demo22331@gmail.com
    password: plaoyhjftmypycvj
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls: 
            enable: true

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1009/eureka/  
  instance:
    hostname: localhost    